name: itemized_share_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  firebase_analytics: ^12.0.4
  firebase_app_check: ^0.4.1+2
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_remote_config: ^6.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  logger: ^2.6.2
  nested: ^1.0.0
  package_info_plus: ^9.0.0
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  slang: ^4.10.1
  slang_flutter: ^4.10.0
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  dependabot_gen: ^1.3.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  icons_launcher: ^3.0.3
  nilts: ^0.25.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  slang_build_runner: ^4.10.0

flutter:
  uses-material-design: true
