name: itemized_share_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  nested: ^1.0.0
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  slang: ^4.10.1
  slang_flutter: ^4.10.0

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  dependabot_gen: ^1.3.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  nilts: ^0.25.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  slang_build_runner: ^4.10.0

flutter:
  uses-material-design: true
